Anki.nvim is a Neovim plugin that allows you to interact with Anki using [[https://ankiweb.net/shared/info/2055492159][AnkiConnect]].
It allows you to create, edit, and manage your Anki notes and decks directly from neovim.

* Features
- Three-pane UI: Navigate decks, notes, and edit content in a file-explorer-like interface within Neovim.
- Persistent 'Default' Deck: The 'Default' deck will always appear in the deck pane, even if deleted, because Anki automatically recreates it as needed.
- Deck Management: Create, rename, and delete Anki decks from within Neovim.
- Note Management: Create, edit, move and delete notes in any deck.
- Model Selection: Choose the note model when creating notes.
- Open in Anki GUI: Jump directly to the selected deck or note in the Anki desktop application.
- Automatic UI Refresh: Deck and notes list refresh automatically after changes.


* Dependencies
- [[https://github.com/daurnimator/lua-http][lua-http]]
- [[https://ankiweb.net/shared/info/2055492159][AnkiConnect]] (Anki Add-on)

* Installation
Using =lazy.nvim=:
#+begin_src lua
{
  "0fflineuser/anki.nvim",
  dependencies = {
        {
            "vhyrro/luarocks.nvim",
            priority = 1000,
            opts = {
                rocks = { "http" },
            },
        },
  },
  opts = {
    url = "http://localhost:8765",
    timeout = 500,
	  prefix = "<leader>a",
	  default_mappings = true,
    gui_browse_enabled = true,
    create_user_commands = true,
  },
  config = true
}
#+end_src

* Configuration
You can customize the plugin by passing a table to the =setup()= function. Here are the default options:
#+begin_src lua
  require("anki").setup({
    -- The URL of your AnkiConnect server
    url = "http://localhost:8765",
    -- The timeout for requests to AnkiConnect, in milliseconds
    timeout = 500,
    -- The key to open the 'Anki UI' tab
	  prefix = "<leader>a",
    -- Automatically map the 'Anki UI' to 'prefix'
	  default_mappings = true,
    -- Whether to automatically open the Anki GUI to the relevant deck/note
    gui_browse_enabled = true,
    -- Whether to create the 'Anki' command
    create_user_commands = true,
  })
#+end_src

* Usage
The plugin is centered around a single command, =:Anki=, which opens a dedicated UI in a new tab.

This UI has three panes:
- *Notes* (top-left): A list of notes in the selected deck.
- *Decks* (bottom-left): A file-explorer view of your decks.
- *Editor* (right): Where the note editor opens.

Each pane has its own set of keymaps. You can press =?= in any pane to see the available shortcuts for that specific context.

** Deck Browser Keymaps
| Keymap | Description                             |
|--------+-----------------------------------------|
| =?=    | Show this help window                   |
| =q=    | Close the Anki UI tab                   |
| =<CR>= | Select a deck and show its notes        |
| =d=    | Delete deck under cursor                |
| =c=    | Create a deck                           |
| =a=    | Add a note to the deck under the cursor |
| =m=    | Rename deck under the cursor            |
| =o=    | Open the selected deck in the Anki GUI  |
| =r=    | Refresh decks                           |

** Note Browser Keymaps
| Keymap | Description                               |
|--------+-------------------------------------------|
| =?=    | Show this help window                     |
| =q=    | Close the Anki UI tab                     |
| =<CR>= | Edit the selected note in the editor pane |
| =d=    | Delete the selected note                  |
| =o=    | Open the selected note in the Anki GUI    |
| =r=    | Refresh notes                             |


** Note Editor Keymaps
| Keymap      | Description                                     |
|-------------+-------------------------------------------------|
| =?=         | Show this help window                           |
| =<leader>w= | *W*rite/Send the current note to Anki           |
| =<leader>p= | *P*ull the latest version of the note from Anki |
| =<leader>r= | *R*emove/Delete the note from Anki              |
| =<leader>k= | *K*ill/Close the note editor buffers            |
