local ankiconnect = require("anki.ankiconnect")

describe("anki.ankiconnect template methods", function()
	describe("model_templates", function()
		it("throws error when modelName is not a string", function()
			assert.has_error(function()
				ankiconnect.model_templates(123, function() end)
			end, "[anki.nvim][ankiconnect] Expected a string as modelName")
		end)
	end)

	describe("model_styling", function()
		it("throws error when modelName is not a string", function()
			assert.has_error(function()
				ankiconnect.model_styling(123, function() end)
			end, "[anki.nvim][ankiconnect] Expected a string as modelName")
		end)
	end)

	describe("update_model_templates", function()
		it("throws error when model is not a table", function()
			assert.has_error(function()
				ankiconnect.update_model_templates("not a table", function() end)
			end, "[anki.nvim][ankiconnect] Expected a table as model")
		end)
	end)

	describe("update_model_styling", function()
		it("throws error when model is not a table", function()
			assert.has_error(function()
				ankiconnect.update_model_styling("not a table", function() end)
			end, "[anki.nvim][ankiconnect] Expected a table as model")
		end)
	end)

	describe("create_model", function()
		it("throws error when modelName is not a string", function()
			assert.has_error(function()
				ankiconnect.create_model(123, {}, {}, nil, nil, function() end)
			end, "[anki.nvim][ankiconnect] Expected a string as modelName")
		end)

		it("throws error when inOrderFields is not a table", function()
			assert.has_error(function()
				ankiconnect.create_model("Test", "not a table", {}, nil, nil, function() end)
			end, "[anki.nvim][ankiconnect] Expected a table as inOrderFields")
		end)

		it("throws error when cardTemplates is not a table", function()
			assert.has_error(function()
				ankiconnect.create_model("Test", {}, "not a table", nil, nil, function() end)
			end, "[anki.nvim][ankiconnect] Expected a table as cardTemplates")
		end)
	end)
end)
