local media_browser = require("anki.ui.media_browser")
local media = require("anki.media")

describe("anki.ui.media_browser", function()
	describe("icon helpers", function()
		it("detect_media_type returns correct types for browser items", function()
			assert.are.equal("image", media.detect_media_type("photo.png"))
			assert.are.equal("audio", media.detect_media_type("sound.mp3"))
			assert.are.equal("video", media.detect_media_type("clip.mp4"))
			assert.is_nil(media.detect_media_type("file.txt"))
		end)

		it("media_reference generates correct references for all media types", function()
			assert.are.equal('<img src="photo.png">', media.media_reference("photo.png"))
			assert.are.equal("[sound:sound.mp3]", media.media_reference("sound.mp3"))
			assert.are.equal("[sound:clip.mp4]", media.media_reference("clip.mp4"))
		end)
	end)

	describe("close", function()
		it("does not error when called with no browser open", function()
			assert.has_no.errors(function()
				media_browser.close()
			end)
		end)

		it("does not error when called multiple times", function()
			assert.has_no.errors(function()
				media_browser.close()
				media_browser.close()
			end)
		end)
	end)

	describe("select_and_insert", function()
		it("does not error when no browser is open", function()
			assert.has_no.errors(function()
				media_browser.select_and_insert()
			end)
		end)
	end)

	describe("config", function()
		it("media_browser_preview defaults to true", function()
			local config = require("anki.config")
			assert.is_true(config.defaults.media_browser_preview)
		end)
	end)
end)
