local notification = require("anki.notification")

describe("anki.notification", function()
	describe("info", function()
		it("throws error when message is not a string", function()
			assert.has_error(function()
				notification.info(123)
			end, "[anki.nvim][notification] info: message must be a string")
		end)

		it("does not throw error with a string message", function()
			assert.has_no_error(function()
				notification.info("test info")
			end)
		end)
	end)

	describe("warn", function()
		it("throws error when message is not a string", function()
			assert.has_error(function()
				notification.warn(true)
			end, "[anki.nvim][notification] warn: message must be a string")
		end)

		it("does not throw error with a string message", function()
			assert.has_no_error(function()
				notification.warn("test warn")
			end)
		end)
	end)

	describe("error", function()
		it("throws error when message is not a string", function()
			assert.has_error(function()
				notification.error({})
			end, "[anki.nvim][notification] error: message must be a string")
		end)

		it("does not throw error with a string message", function()
			assert.has_no_error(function()
				notification.error("test error")
			end)
		end)
	end)
end)
