describe("windows option setting", function()
	it("sets wrap option using window scope without error", function()
		vim.cmd("vnew")
		local win = vim.api.nvim_get_current_win()
		local buf = vim.api.nvim_win_get_buf(win)
		assert.has_no.errors(function()
			vim.api.nvim_set_option_value("wrap", false, { win = win })
		end)
		vim.api.nvim_win_close(win, true)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)

	it("errors when setting window-local wrap option with buf scope", function()
		local buf = vim.api.nvim_create_buf(true, true)
		assert.has_error(function()
			vim.api.nvim_set_option_value("wrap", false, { buf = buf })
		end)
		vim.api.nvim_buf_delete(buf, { force = true })
	end)
end)
